run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - paralleltest
    - perfsprint
    - prealloc
    - testpackage
    - tparallel
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

    # deprecated
    - tenv

    # disabled because of generics
    - rowserrcheck
    - wastedassign

    # TODO: fix
    - copyloopvar
    - cyclop
    - errcheck
    - forbidigo
    - goconst
    - gocyclo
    - govet
    - inamedparam
    - intrange
    - maintidx
    - nilnil
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle

  skip-dirs:
    - gen

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupword
        - forcetypeassert
        - goconst
        - maintidx
        - noctx
    - linters:
        - staticcheck
      text: 'SA1019: "github.com/golang/protobuf' # TODO

linters-settings:
  cyclop:
    max-complexity: 25
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G115
  maintidx:
    under: 30
  stylecheck:
    checks:
    - all
    # revive has same rules
    - -ST1005
    - -ST1006
