name: cross-build
on:
  push:
    branches:
      - cross-build
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.matrix.outputs.versions }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
    - name: Generate matrix
      id: matrix
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -eu
        versions=$(make matrix)
        echo $versions
        echo "versions=$versions" >> $GITHUB_OUTPUT
  build:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(needs.matrix.outputs.go-version) }}
    env:
      SNAPSHOT: true
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: GO_VERSION=${{ matrix.go-version }} make build/ci
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.go-version }}
        path: ${{ github.workspace }}/dist/
